// Offline city search. The dataset (src/data/cities.json) is a curated list of
// the world's most populous cities, each with coordinates and an IANA time zone,
// generated by scripts/build-cities.mjs. No network / API keys required.

import cities from './data/cities.json';

// A few Latin letters don't reduce to ASCII under NFD (they're not "base +
// accent"), so map them explicitly. Curly/straight apostrophes are dropped so
// "Xian" matches "Xi'an". Keys are the lower-cased form (fold() lower-cases
// first), which also covers their uppercase variants (Ł→ł, Ø→ø, …).
const FOLD_MAP = {
  ł: 'l', ø: 'o', đ: 'd', ð: 'd', ı: 'i', ß: 'ss',
  æ: 'ae', œ: 'oe', þ: 'th', ħ: 'h',
  '’': '', '‘': '', 'ʼ': '', "'": ''
};

/**
 * Diacritic-insensitive fold for comparison only: decompose accents (NFD),
 * drop the combining marks (\p{Mn}), lower-case, then apply the special-letter
 * map. "Zürich" and "Zurich" both fold to "zurich"; the accented name is still
 * what we display.
 */
function fold(str) {
  let out = '';
  for (const ch of str.normalize('NFD').replace(/\p{Mn}/gu, '').toLowerCase()) {
    out += FOLD_MAP[ch] ?? ch;
  }
  return out;
}

// Pre-fold names once for fast, accent-insensitive matching.
const index = cities.map((c) => ({ ...c, _q: fold(c.name) }));

/**
 * Return up to `limit` cities matching `query`, ranked so that prefix matches
 * and larger cities come first. Empty query → no results.
 */
export function searchCities(query, limit = 7) {
  const q = fold(query.trim());
  if (!q) return [];

  const scored = [];
  for (const c of index) {
    const pos = c._q.indexOf(q);
    if (pos === -1) continue;
    // Rank: exact/prefix beats substring; population breaks ties.
    const rank = (pos === 0 ? 0 : 1e12) - c.pop + pos * 1e6;
    scored.push({ city: c, rank });
  }

  scored.sort((a, b) => a.rank - b.rank);
  return scored.slice(0, limit).map(({ city }) => ({
    name: city.name,
    country: city.country,
    lat: city.lat,
    lng: city.lng,
    tz: city.tz
  }));
}
